#!/bin/bash
#Created by Mark Mon Monteros
#	*** AdobeConnect Fix Script ***

echo "*** AdobeConnect Fix Script ***"
echo 'Enter your local password: "concentrix"'
dscacheutil -flushcache
echo Flushing DNS . . .

mDNS1=$(pgrep mDNSResponder | sed -n 1p)
mDNS2=$(pgrep mDNSResponder | sed -n 2p)
SafariPS=$(ps aux | grep Safari | grep -v ttys | awk '{print $2}' > /tmp/SafariPS.txt)
AdobePS=$(ps aux | grep Adobe | grep -v ttys | awk '{print $2}' > /tmp/AdobePS.txt)
FortiPS=$(ps aux | grep Forti | grep -v ttys | awk '{print $2}' > /tmp/FortiPS.txt)

declare Safari=(`cat /tmp/SafariPS.txt`)
declare AdobeC=(`cat /tmp/AdobePS.txt`)
declare Forti=(`cat /tmp/FortiPS.txt`)

echo Closing Safari...
countkSafari=$(echo ${#Safari[*]})

for (( i=0; i<$countkSafari; i++ ));
do
    kill -9 ${Safari[$i]} > /dev/null 2>&1
done

echo Closing Adobe Connect...
countkAdobeC=$(echo ${#AdobeC[*]})

for (( i=0; i<$countkAdobeC; i++ ));
do
    kill -9 ${AdobeC[$i]} > /dev/null 2>&1
done

echo Closing FortiClient...
countkForti=$(echo ${#Forti[*]})

for (( i=0; i<$countkForti; i++ ));
do
    kill -9 ${Forti[$i]} > /dev/null 2>&1
done

sudo killall Safari > /dev/null 2>&1
sudo killall Adobe\ Connect > /dev/null 2>&1
sudo killall FortiClient > /dev/null 2>&1

echo       
echo Hang-Up mDNSResponder...
sudo kill -HUP $mDNS1 $mDNS2
echo Backing Up Safari Bookmarks...
sudo cp -R ~/Library/Safari/Bookmarks.plist ~/Desktop
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
echo Clearing COOKIES...
sudo rm -rf ~/Library/Cookies/* > /dev/null 2>&1
echo Clearing HISTORY...
sudo rm -rf ~/Library/Safari/* > /dev/null 2>&1
sudo rm -rf ~/Library/Saved\ Application\ State/* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Safari* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Web* > /dev/null 2>&1
sudo rm -rf ~/Library/PubSub/Database/* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
sleep 3
echo Restoring Safari Bookmarks...
mv ~/Desktop/Bookmarks.plist ~/Library/Safari/
echo Clearing AdobeConnect Settings...
sudo rm -rf ~/Library/Preferences/Macromedia*
sudo rm -rf ~/Library/Preferences/adobeconnectaddin.plist

sudo rm -rf /tmp/*.txt > /dev/null 2>&1


echo C O M P L E T E !
killall Terminal
