#!/bin/bash
#Created by Mark Mon Monteros
#	*** ADP Fix Script ***

echo "*** ADP Fix Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

declare mDNS=(`ps -ax | grep -i mDNSResponder | grep -v ttys | awk '{print$1}'`)
declare Sfari=(`ps -ax | grep -i Safari | grep -v ttys | awk '{print $1}'`)

echo Closing Safari...
for (( i=0; i<${#Sfari[*]}; i++ ));
do
    sudo kill -9 ${Sfari[$i]} > /dev/null 2>&1
done
sudo killall Safari > /dev/null 2>&1

echo Hang-Up mDNSResponder...
for (( i=0; i<${#mDNS[*]}; i++ ));
do
    sudo kill -HUP ${mDNS[$i]} > /dev/null 2>&1
done

echo                 
echo Backing Up Safari Bookmarks...
sudo cp -R ~/Library/Safari/Bookmarks.plist ~/Desktop
echo Clearing Java Plug-ins...
sudo rm -rf /Library/Preferences/com.oracle* > /dev/null 2>&1
sudo rm -rf /Library/Java* > /dev/null 2>&1
sudo rm -rf /Library/Internet \Plug \Ins/Java* > /dev/null 2>&1
sudo rm -rf ~/Library/Oracle* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.oracle* > /dev/null 2>&1
sudo rm -rf /Library/Internet\ Plug-Ins/Java*
sudo rm -rf ~/Library/Application\ Support/Oracle*
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
echo Clearing COOKIES...
sudo rm -rf ~/Library/Cookies/* > /dev/null 2>&1
echo Clearing HISTORY...
sudo rm -rf ~/Library/Safari/* > /dev/null 2>&1
sudo rm -rf ~/Library/Saved\ Application\ State/* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Safari* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Web* > /dev/null 2>&1
sudo rm -rf ~/Library/PubSub/Database/* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
sleep 3
echo Restoring Safari Bookmarks...
sudo mv ~/Desktop/Bookmarks.plist ~/Library/Safari/
echo Disabling Safari Pop-ups...
open -g /Applications/Safari.app
sleep 1

WHO=$(whoami > /tmp/whoami.txt)
WHOAMI=$(cat /tmp/whoami.txt)
HOMEDIR=$(dscl . -read /Users/"$WHOAMI" NFSHomeDirectory | awk '{print$2}')
LIB=$(echo /Library/Preferences/com.apple.Safari.plist)
WRITE=$(echo $HOMEDIR$LIB)
sudo killall Safari


chmod 777 $WRITE
sleep 2
function writeplist() {
defaults write $WRITE com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically "<true />"
}
sleep 1
writeplist

echo Please download Java Runtime Environment Plugin...
open /Applications/Safari.app -g http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

echo C O M P L E T E !
echo
echo
echo "Download latest Adobe Flash Player plugin for macOS"
echo "Download latest Java JRE Plugin for macOS at http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html"
echo "or type this keyword on the Search Engine --> JRE download OSX"
echo
echo          