#!/bin/bash
#Created by Mark Mon Monteros
#	*** AHA Fix Script ***

echo "*** AHA Fix Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

mDNS1=$(pgrep mDNSResponder | sed -n 1p)
mDNS2=$(pgrep mDNSResponder | sed -n 2p)
SafariPS=$(ps aux | grep -i Safari | grep -v ttys | awk '{print $2}' > /tmp/SafariPS.txt)
SafeViewPS=$(ps aux | grep -i SafeView | grep -v ttys | awk '{print $2}' > /tmp/SafeViewPS.txt)
iLogPS=$(ps aux | grep -i iLog | grep -v ttys | awk '{print $2}' > /tmp/iLogPS.txt)
ApplePS=$(ps aux | grep -i AppleConnect | grep -v ttys | awk '{print $2}' > /tmp/ApplePS.txt)
AvalonPS=$(ps aux | grep -i Avalon | grep -v ttys | awk '{print $2}' > /tmp/AvalonPS.txt)

declare Safari=(`cat /tmp/SafariPS.txt`)
declare SafeView=(`cat /tmp/SafeViewPS.txt`)
declare iLog=(`cat /tmp/iLogPS.txt`)
declare Apple=(`cat /tmp/ApplePS.txt`)
declare Avalon=(`cat /tmp/AvalonPS.txt`)

echo Closing Safari...
countkSafari=$(echo ${#Safari[*]})

for (( i=0; i<$countkSafari; i++ ));
do
    sudo kill -9 ${Safari[$i]} > /dev/null 2>&1
done

echo Closing SafeView...
countkSafeView=$(echo ${#SafeView[*]})

for (( i=0; i<$countkSafeView; i++ ));
do
    sudo kill -9 ${SafeView[$i]} > /dev/null 2>&1
done

echo Closing iLog...
countkiLog=$(echo ${#iLog[*]})

for (( i=0; i<$countkiLog; i++ ));
do
    sudo kill -9 ${iLog[$i]} > /dev/null 2>&1
done

echo Closing AppleConnect...
countkApple=$(echo ${#Apple[*]})

for (( i=0; i<$countkApple; i++ ));
do
    sudo kill -9 ${Apple[$i]} > /dev/null 2>&1
done
echo Closing Avalon...
countkAvalon=$(echo ${#Avalon[*]})

for (( i=0; i<$countkAvalon; i++ ));
do
    sudo kill -9 ${Avalon[$i]} > /dev/null 2>&1
done

sudo killall Safari > /dev/null 2>&1
sudo killall iLog > /dev/null 2>&1
sudo killall SafeView > /dev/null 2>&1
sudo killall AppleConnectAgent > /dev/null 2>&1
sudo killall Avalon > /dev/null 2>&1

echo    
echo Hang-Up mDNSResponder...
sudo kill -HUP $mDNS1 $mDNS2 > /dev/null 2>&1
echo Backing Up Safari Bookmarks...
sudo cp -R ~/Library/Safari/Bookmarks.plist ~/Desktop
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
sudo rm -rf ~/Library/Cookies/* > /dev/null 2>&1
sudo rm -rf ~/Library/Safari/* > /dev/null 2>&1
sudo rm -rf ~/Library/Saved\ Application\ State/* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Safari* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Web* > /dev/null 2>&1
sudo rm -rf ~/Library/PubSub/Database/* > /dev/null 2>&1
sudo rm -rf /Library/LaunchDaemons/com.apple.* > /dev/null 2>&1
sudo rm -rf /Library/LaunchAgents/com.apple.* > /dev/null 2>&1
sudo rm -rf ~/Library/LaunchAgents/* > /dev/null 2>&1
echo Clearing AppleConnect Settings...
sudo /Library/Application\ Support/AppleConnect/Uninstall\ AppleConnect.app/Contents/Resources/appleconnectuninstall > /dev/null 2>&1
wait
sudo rm -rf /Library/Application\ Support/AppleConnect* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.ist* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.ist* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/ByHost/com.apple.ist* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.alf* > /dev/null 2>&1
echo Clearing iLog Settings...
sudo rm -rf ~/Library/Application\ Support/ILOG* > /dev/null 2>&1
sudo rm -rf ~/ilog* > /dev/null 2>&1
echo Clearing SafeView Settings...
sudo rm -rf /Library/Application\ Support/SafeView* > /dev/null 2>&1
sudo rm -rf ~/Library/Application\ Support/SafeView* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.ids.service.com.apple.private.alloy.safeview.plist > /dev/null 2>&1
echo Clearing Avalon Settings...
sudo rm -rf ~/Library/Preferences/com.apple.ipTelephony.plist > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.softphone.plist > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Telephony* > /dev/null 2>&1
sudo rm -rf ~/Library/Application\ Support/Avalon* > /dev/null 2>&1
sudo rm -rf ~/Library/Application\ Support/ADVoice* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
sleep 3
echo Importing Safari Bookmarks...
sudo mv ~/Desktop/Bookmarks.plist ~/Library/Safari/
sleep 1
echo Set Computer Name...
NAME=$(security find-certificate -a ~/Library/Keychains/login.keychain | grep -A 1 CONCENTRIX-GVW-P-CA | tail -n 1 | cut -d \" -f4 | tr -d \' | sed 's/\\[0-9]*//g');
DEPT="-AAHA"
HOST=$NAME$DEPT
sudo scutil --set ComputerName "$HOST"
sudo scutil --set HostName "$HOST"
echo Changing Ownership...
sudo chown -R root:wheel /Applications/SafeView.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/iLog.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/AppleConnect.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/FortiClient.app > /dev/null 2>&1
sleep 3
echo Changing Permissions...
sudo chmod -R 755 /Applications/SafeView.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/iLog.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/AppleConnect.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/FortiClient.app > /dev/null 2>&1
sleep 2

echo                     
echo Downloading AppleConnect...
sudo jamf policy -event appleconnect > /tmp/appleDL.txt
appleDL=$(cat /tmp/appleDL.txt | sed -n 2p | awk '{print$1}')
if [[ $appleDL == "Executing" ]]; then
    echo "AppleConnect Installed Successfully!!!"
else
    echo "AppleConnect Download FAILED!"
fi
sudo killall AppleConnect > /dev/null 2>&1

echo          
echo Checking JAVA on system...                               
java -version > /dev/null 2>&1
echo $? > /tmp/javaVER.txt
javaVER=$(cat /tmp/javaVER.txt)
if [[ $javaVER -eq 0 ]]; then
    echo "JAVA Detected..!"
else
    echo "No JAVA detected"
    echo "Downloading JAVA..."
    sudo jamf policy -event ilogjava > /tmp/javaDL.txt
    javaDL=$(cat /tmp/javaDL.txt | sed -n 2p | awk '{print$1}')
        if [[ $javaDL == "Executing" ]]; then
            echo "JAVA Installed Successfully!!!"
        else
            echo "JAVA Download FAILED!"
        fi
fi
javakill=$(pgrep -i java | grep -v ttys)
sudo kill -9 $javakill > /dev/null 2>&1

sleep 3
echo                      
echo Clearing Network Settings...
sudo rm -rf /Library/Preferences/SystemConfiguration/* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.network* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/P2P* > /dev/null 2>&1
sudo rm -rf /System/Library/NetworkServiceProxy/* > /dev/null 2>&1

open -g /Applications/AppleConnect.app > /dev/null 2>&1
echo $? > /tmp/appctest.txt
sudo killall AppleConnect > /dev/null 2>&1
appctest=$(cat /tmp/appctest.txt)
if [[ $appctest -ne 0 ]]; then
    function appcerror() {
    sudo touch appcerror.py
    sudo chmod 777 appcerror.py
    echo '#!/usr/bin/python' >> appcerror.py
    echo 'from Tkinter import *' >> appcerror.py
    echo 'import tkMessageBox' >> appcerror.py
    echo 'root = Tk()' >> appcerror.py
    echo 'root.withdraw()' >> appcerror.py
    echo 'tkMessageBox.showerror(title="Error!", message="AppleConnect download FAILED!\n\nPlease download and install AppleConnect manually.")' >> appcerror.py
    }
    appcerror
    sudo ./appcerror.py > /dev/null 2>&1
fi
sudo rm -rf appcerror.py > /dev/null 2>&1

java -version
echo $? > /tmp/javatest.txt
javakill=$(pgrep -i java | grep -v ttys)
sudo kill -9 $javakill > /dev/null 2>&1
javatest=$(cat /tmp/javatest.txt)
if [[ $javatest -ne 0 ]]; then
    function javaerror() {
    sudo touch javaerror.py
    sudo chmod 777 javaerror.py
    echo '#!/usr/bin/python' >> javaerror.py
    echo 'from Tkinter import *' >> javaerror.py
    echo 'import tkMessageBox' >> javaerror.py
    echo 'root = Tk()' >> javaerror.py
    echo 'root.withdraw()' >> javaerror.py
    echo 'tkMessageBox.showerror(title="Error!", message="JAVA download FAILED!\n\nPlease download and install JAVA manually.")' >> javaerror.py
    }
    javaerror
    sudo ./javaerror.py > /dev/null 2>&1
fi
sudo rm -rf javaerror.py > /dev/null 2>&1

sudo rm -rf /tmp/*.txt > /dev/null 2>&1
echo
echo              
echo C O M P L E T E D !
echo                          
echo    
echo Restarting MAC...
echo                
for (( i=10; i>=1; i-- ));
do
    if [[ i -eq 1 ]]; then
        echo
        echo rebooting NOW.. !
        echo            
        sudo reboot
    else
        echo $i..
        sleep 1
        javakill=$(pgrep -i java | grep -v ttys)
        sudo kill -9 $javakill > /dev/null 2>&1
    fi
done

sudo killall Terminal
