#!/bin/bash
#   Created by WAH-IT PHL L2
#	*** AHA Fix Script ***

echo "*** AHA Fix Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

declare mDNS=(`ps -ax | grep -i mDNSResponder | grep -v ttys | awk '{print$1}'`)
declare Sfari=(`ps -ax | grep -i Safari | grep -v ttys | awk '{print $1}'`)
declare SafeView=(`ps -ax | grep -i SafeView | grep -v ttys | awk '{print $1}'`)
declare iLog=(`ps -ax | grep -i iLog | grep -v ttys | awk '{print $1}'`)
declare Apple=(`ps -ax | grep -i AppleConnect | grep -v ttys | awk '{print $1}'`)
declare Avalon=(`ps -ax | grep -i Avalon | grep -v ttys | awk '{print $1}'`)

echo Closing Safari...
for (( i=0; i<${#Sfari[*]}; i++ ));
do
    sudo kill -9 ${Sfari[$i]} > /dev/null 2>&1
done
sudo killall Safari > /dev/null 2>&1

echo Closing SafeView...
for (( i=0; i<${#SafeView[*]}; i++ ));
do
    sudo kill -9 ${SafeView[$i]} > /dev/null 2>&1
done
sudo killall SafeView > /dev/null 2>&1

echo Closing iLog...
for (( i=0; i<${#iLog[*]}; i++ ));
do
    sudo kill -9 ${iLog[$i]} > /dev/null 2>&1
done
sudo killall iLog > /dev/null 2>&1

echo Closing AppleConnect...
for (( i=0; i<${#Apple[*]}; i++ ));
do
    sudo kill -9 ${Apple[$i]} > /dev/null 2>&1
done
sudo killall AppleConnectAgent > /dev/null 2>&1

echo Closing Avalon...
for (( i=0; i<${#Avalon[*]}; i++ ));
do
    sudo kill -9 ${Avalon[$i]} > /dev/null 2>&1
done
sudo killall Avalon > /dev/null 2>&1

echo Hang-Up mDNSResponder...
for (( i=0; i<${#mDNS[*]}; i++ ));
do
    sudo kill -HUP ${mDNS[$i]} > /dev/null 2>&1
done

echo                 
echo Backing Up Safari Bookmarks...
sudo cp -R ~/Library/Safari/Bookmarks.plist ~/Desktop
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
sudo rm -rf ~/Library/Cookies/* > /dev/null 2>&1
sudo rm -rf ~/Library/Safari/* > /dev/null 2>&1
sudo rm -rf ~/Library/Saved\ Application\ State/* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Safari* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Web* > /dev/null 2>&1
sudo rm -rf ~/Library/PubSub/Database/* > /dev/null 2>&1
sudo rm -rf /Library/LaunchDaemons/com.apple.* > /dev/null 2>&1
sudo rm -rf /Library/LaunchAgents/com.apple.* > /dev/null 2>&1
sudo rm -rf ~/Library/LaunchAgents/* > /dev/null 2>&1
echo Clearing AppleConnect Settings...
sudo /Library/Application\ Support/AppleConnect/Uninstall\ AppleConnect.app/Contents/Resources/appleconnectuninstall > /dev/null 2>&1
wait
sudo rm -rf /Library/Application\ Support/AppleConnect* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.ist* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.ist* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/ByHost/com.apple.ist* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.alf* > /dev/null 2>&1
echo Clearing iLog Settings...
sudo rm -rf ~/Library/Application\ Support/ILOG* > /dev/null 2>&1
sudo rm -rf ~/ilog* > /dev/null 2>&1
echo Clearing SafeView Settings...
sudo rm -rf /Library/Application\ Support/SafeView* > /dev/null 2>&1
sudo rm -rf ~/Library/Application\ Support/SafeView* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.ids.service.com.apple.private.alloy.safeview.plist > /dev/null 2>&1
echo Clearing Avalon Settings...
sudo rm -rf ~/Library/Preferences/com.apple.ipTelephony.plist > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.softphone.plist > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Telephony* > /dev/null 2>&1
sudo rm -rf ~/Library/Application\ Support/Avalon* > /dev/null 2>&1
sudo rm -rf ~/Library/Application\ Support/ADVoice* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
sleep 3
echo Importing Safari Bookmarks...
sudo mv ~/Desktop/Bookmarks.plist ~/Library/Safari/
sleep 1
echo Set Computer Name...
NAME=(`security find-certificate -a ~/Library/Keychains/login.keychain | grep -A 1 CONCENTRIX-GVW-P-CA | tail -n 1 | cut -d \" -f4 | tr -d \' | sed 's/\\[0-9]*//g'`)
DEPT="-AAHA"
HOST=$NAME$DEPT
sudo scutil --set ComputerName "$HOST"
sudo scutil --set HostName "$HOST"
echo Changing Ownership...
sudo chown -R root:wheel /Applications/SafeView.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/iLog.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/AppleConnect.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/FortiClient.app > /dev/null 2>&1
sleep 3
echo Changing Permissions...
sudo chmod -R 755 /Applications/SafeView.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/iLog.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/AppleConnect.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/FortiClient.app > /dev/null 2>&1
sleep 2

echo                      
echo Clearing Network Settings...
sudo rm -rf /Library/Preferences/SystemConfiguration/* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.network* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/P2P* > /dev/null 2>&1
sudo rm -rf /System/Library/NetworkServiceProxy/* > /dev/null 2>&1

sudo rm -rf /tmp/*.txt > /dev/null 2>&1
echo
echo              
echo C O M P L E T E D !
echo                          
echo    
echo Restarting MAC...
echo                
for (( i=10; i>=1; i-- ));
do
    if [[ i -eq 1 ]]; then
        echo
        echo rebooting NOW.. !
        echo            
        sudo reboot
    else
        echo $i..
        sleep 1
    fi
done

sudo killall Terminal
