#!/bin/bash
#   Created by WAH-IT PHL L2
#	*** AHA Fix Script ***

echo "*** AHA Fix Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

declare mDNS=(`ps -ax | grep -i mDNSResponder | grep -v ttys | awk '{print$1}'`)
declare Sfari=(`ps -ax | grep -i Safari | grep -v ttys | awk '{print $1}'`)
declare SafeView=(`ps -ax | grep -i SafeView | grep -v ttys | awk '{print $1}'`)
declare iLog=(`ps -ax | grep -i iLog | grep -v ttys | awk '{print $1}'`)
declare Apple=(`ps -ax | grep -i AppleConnect | grep -v ttys | awk '{print $1}'`)
declare Avalon=(`ps -ax | grep -i Avalon | grep -v ttys | awk '{print $1}'`)

echo Closing Safari...
for (( i=0; i<${#Sfari[*]}; i++ ));
do
    sudo kill -9 ${Sfari[$i]} > /dev/null 2>&1
done
sudo killall Safari > /dev/null 2>&1

echo Closing SafeView...
for (( i=0; i<${#SafeView[*]}; i++ ));
do
    sudo kill -9 ${SafeView[$i]} > /dev/null 2>&1
done
sudo killall SafeView > /dev/null 2>&1

echo Closing iLog...
for (( i=0; i<${#iLog[*]}; i++ ));
do
    sudo kill -9 ${iLog[$i]} > /dev/null 2>&1
done
sudo killall iLog > /dev/null 2>&1

echo Closing AppleConnect...
for (( i=0; i<${#Apple[*]}; i++ ));
do
    sudo kill -9 ${Apple[$i]} > /dev/null 2>&1
done
sudo killall AppleConnectAgent > /dev/null 2>&1

echo Closing Avalon...
for (( i=0; i<${#Avalon[*]}; i++ ));
do
    sudo kill -9 ${Avalon[$i]} > /dev/null 2>&1
done
sudo killall Avalon > /dev/null 2>&1

echo Hang-Up mDNSResponder...
for (( i=0; i<${#mDNS[*]}; i++ ));
do
    sudo kill -HUP ${mDNS[$i]} > /dev/null 2>&1
done

echo                 
echo Backing Up Safari Bookmarks...
sudo cp -R ~/Library/Safari/Bookmarks.plist ~/Desktop
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
sudo rm -rf ~/Library/Cookies/* > /dev/null 2>&1
sudo rm -rf ~/Library/Safari/* > /dev/null 2>&1
sudo rm -rf ~/Library/Saved\ Application\ State/* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Safari* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Web* > /dev/null 2>&1
sudo rm -rf ~/Library/PubSub/Database/* > /dev/null 2>&1
sudo rm -rf /Library/LaunchDaemons/com.apple.* > /dev/null 2>&1
sudo rm -rf /Library/LaunchAgents/com.apple.* > /dev/null 2>&1
sudo rm -rf ~/Library/LaunchAgents/* > /dev/null 2>&1
echo Clearing AppleConnect Settings...
sudo /Library/Application\ Support/AppleConnect/Uninstall\ AppleConnect.app/Contents/Resources/appleconnectuninstall > /dev/null 2>&1
wait
sudo rm -rf /Library/Application\ Support/AppleConnect* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.ist* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.ist* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/ByHost/com.apple.ist* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.alf* > /dev/null 2>&1
echo Clearing iLog Settings...
sudo rm -rf ~/Library/Application\ Support/ILOG* > /dev/null 2>&1
sudo rm -rf ~/ilog* > /dev/null 2>&1
echo Clearing SafeView Settings...
sudo rm -rf /Library/Application\ Support/SafeView* > /dev/null 2>&1
sudo rm -rf ~/Library/Application\ Support/SafeView* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.ids.service.com.apple.private.alloy.safeview.plist > /dev/null 2>&1
echo Clearing Avalon Settings...
sudo rm -rf ~/Library/Preferences/com.apple.ipTelephony.plist > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.softphone.plist > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Telephony* > /dev/null 2>&1
sudo rm -rf ~/Library/Application\ Support/Avalon* > /dev/null 2>&1
sudo rm -rf ~/Library/Application\ Support/ADVoice* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
sleep 3
echo Importing Safari Bookmarks...
sudo mv ~/Desktop/Bookmarks.plist ~/Library/Safari/
sleep 1
echo Set Computer Name...
NAME=$(security find-certificate -a ~/Library/Keychains/login.keychain | grep -A 1 CONCENTRIX-GVW-P-CA | tail -n 1 | cut -d \" -f4 | tr -d \' | sed 's/\\[0-9]*//g');
DEPT="-AAHA"
HOST=$NAME$DEPT
sudo scutil --set ComputerName "$HOST"
sudo scutil --set HostName "$HOST"
echo Changing Ownership...
sudo chown -R root:wheel /Applications/SafeView.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/iLog.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/AppleConnect.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/FortiClient.app > /dev/null 2>&1
sleep 3
echo Changing Permissions...
sudo chmod -R 755 /Applications/SafeView.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/iLog.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/AppleConnect.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/FortiClient.app > /dev/null 2>&1
sleep 2

echo                     
echo Downloading AppleConnect...
sudo jamf policy -event appleconnect > /tmp/appleDL.txt
appleDL=$(cat /tmp/appleDL.txt | sed -n 2p | awk '{print$1}')
if [[ $appleDL == "Executing" ]]; then
    echo "AppleConnect Installed Successfully!!!"
else
    curl -L "https://doc-10-5c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/4hicu1skvf7sa6josqq0d12cboblvlm3/1519754400000/11276154916831075354/*/11kTM-e5DtVVfARgGSr3KPQjT1vMvfAQ3?e=download" > ~/Desktop/AppleConnect.pkg
    ls /Volumes | cut -d @ -f1 | sed -n 1p > /tmp/Volumes.txt
    target=$(cat /tmp/Volumes.txt)
    sudo installer -pkg ~/Desktop/AppleConnect.pkg -tgt /Volumes/"$target"
        if [[ $? -ne 0 ]]; then
            echo "AppleConnect Download FAILED!"
            function apcerror() {
            sudo touch apcerror.py
            sudo chmod 777 apcerror.py
            echo '#!/usr/bin/python' >> apcerror.py
            echo 'from Tkinter import *' >> apcerror.py
            echo 'import tkMessageBox' >> apcerror.py
            echo 'root = Tk()' >> apcerror.py
            echo 'root.withdraw()' >> apcerror.py
            echo 'tkMessageBox.showwarning(title="Error!", message="AppleConnect download FAILED!\n\nPlease download and install AppleConnect manually after system reboots.")' >> apcerror.py
            }
            apcerror
        else
            echo "AppleConnect Installed Successfully!!!"
        fi
fi
sudo killall AppleConnect > /dev/null 2>&1

echo                    
echo Checking iLog version...
mdls -name kMDItemVersion /Applications/iLog.app > /dev/null 2>&1
if [[ $? -ne 0 ]]; then
    echo "No iLog application detected..."
    echo "Downloading iLog..."
    sudo jamf policy -event ilog > /tmp/ilogDL.txt
    ilogDL=$(cat /tmp/ilogDL.txt)
        if [[ $ilogDL == "Executing" ]]; then
            echo "iLog Installed Successfully!!!"
        else
            echo "iLog Download FAILED!"
            function ilogerror() {
            sudo touch ilogerror.py
            sudo chmod 777 ilogerror.py
            echo '#!/usr/bin/python' >> ilogerror.py
            echo 'from Tkinter import *' >> ilogerror.py
            echo 'import tkMessageBox' >> ilogerror.py
            echo 'root = Tk()' >> ilogerror.py
            echo 'root.withdraw()' >> ilogerror.py
            echo 'tkMessageBox.showwarning(title="Error!", message="iLog download FAILED!\n\nPlease download and install iLog manually after system reboots.")' >> ilogerror.py
            }
            ilogerror
        fi
else
    mdls -name kMDItemVersion /Applications/iLog.app | cut -d \" -f2 > /tmp/ilogVER.txt
    ilogVER=$(cat /tmp/ilogVER.txt)
    echo Current iLog version is = "$ilogVER"
        if [[ $ilogVER != "10.3.0.4" ]]; then
            echo Updating iLog to the latest version...
            sudo jamf policy -event ilog > /tmp/ilogDL.txt
            ilogDL=$(cat /tmp/ilogDL.txt)
                if [[ $ilogDL == "Executing" ]]; then
                    echo "iLog Successfully Updated to the latest version!!!"
                else
                    echo "iLog Update FAILED!"
                    function ilogerror() {
                    sudo touch ilogerror.py
                    sudo chmod 777 ilogerror.py
                    echo '#!/usr/bin/python' >> ilogerror.py
                    echo 'from Tkinter import *' >> ilogerror.py
                    echo 'import tkMessageBox' >> ilogerror.py
                    echo 'root = Tk()' >> ilogerror.py
                    echo 'root.withdraw()' >> ilogerror.py
                    echo 'tkMessageBox.showwarning(title="Error!", message="iLog download FAILED!\n\nPlease download and install iLog manually after system reboots.")' >> ilogerror.py
                    }
                    ilogerror
                fi
        else
            echo "iLog is already on the latest version."
        fi
fi
sudo killall iLog > /dev/null 2>&1

echo                    
echo Checking SafeView version...
mdls -name kMDItemVersion /Applications/SafeView.app > /dev/null 2>&1
if [[ $? -ne 0 ]]; then
    echo "No SafeView application detected"
else
    echo Current SafeView version is = `mdls -name kMDItemVersion /Applications/SafeView.app | cut -d \" -f2`
fi
echo Downloading SafeView...
curl -L "https://doc-04-5c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/um65pmrivfartiekpr1padr6rjq9n7f1/1519999200000/11276154916831075354/*/1jRX825yyVpNgw_t51qzAl2TiuOBJJ89S?e=download" > ~/Desktop/SafeView.pkg
if [[ $? -ne 0 ]]; then
    echo "SafeView Download FAILED!"
    function safeerror() {
    sudo touch safeerror.py
    sudo chmod 777 safeerror.py
    echo '#!/usr/bin/python' >> safeerror.py
    echo 'from Tkinter import *' >> safeerror.py
    echo 'import tkMessageBox' >> safeerror.py
    echo 'root = Tk()' >> safeerror.py
    echo 'root.withdraw()' >> safeerror.py
    echo 'tkMessageBox.showwarning(title="Error!", message="SafeView download FAILED!\n\nPlease download and install SafeView manually after system reboots.")' >> safeerror.py
    }
    safeerror
else
    echo Installing SafeView...
    ls /Volumes | cut -d @ -f1 | sed -n 1p > /tmp/Volumes.txt
    target=$(cat /tmp/Volumes.txt)
    sudo installer -pkg ~/Desktop/SafeView.pkg -tgt /Volumes/"$target" 
        if [[ $? -ne 0 ]]; then
            echo "SafeView Download FAILED!"
            function safeerror() {
            sudo touch safeerror.py
            sudo chmod 777 safeerror.py
            echo '#!/usr/bin/python' >> safeerror.py
            echo 'from Tkinter import *' >> safeerror.py
            echo 'import tkMessageBox' >> safeerror.py
            echo 'root = Tk()' >> safeerror.py
            echo 'root.withdraw()' >> safeerror.py
            echo 'tkMessageBox.showwarning(title="Error!", message="SafeView download FAILED!\n\nPlease download and install SafeView manually after system reboots.")' >> safeerror.py
            }
            safeerror
        else
            echo "SafeView Installed Successfully!!!"
        fi
fi   
sudo rm -rf SafeView.pkg > /dev/null 2>&1
sudo killall SafeView > /dev/null 2>&1

echo          
echo Checking JAVA on system...                               
java -version > /dev/null 2>&1
echo $? > /tmp/javaVER.txt
javaVER=$(cat /tmp/javaVER.txt)
if [[ $javaVER -eq 0 ]]; then
    echo "JAVA Detected..!"
else
    echo "No JAVA detected"
    javakill=$(ps -ax | grep -i java | grep -v ttys)
    sudo kill -9 $javakill > /dev/null 2>&1
    echo "Downloading JAVA..."
    sudo jamf policy -event ilogjava > /tmp/javaDL.txt
    javaDL=$(cat /tmp/javaDL.txt | sed -n 2p | awk '{print$1}')
        if [[ $javaDL == "Executing" ]]; then
            echo "JAVA Installed Successfully!!!"
        else
            echo "JAVA Download FAILED!"
            function javaerror() {
            sudo touch javaerror.py
            sudo chmod 777 javaerror.py
            echo '#!/usr/bin/python' >> javaerror.py
            echo 'from Tkinter import *' >> javaerror.py
            echo 'import tkMessageBox' >> javaerror.py
            echo 'root = Tk()' >> javaerror.py
            echo 'root.withdraw()' >> javaerror.py
            echo 'tkMessageBox.showwarning(title="Error!", message="JAVA download FAILED!\n\nPlease download and install JAVA manually after system reboots.")' >> javaerror.py
            }
            javaerror
        fi
fi

sleep 3
echo                      
echo Clearing Network Settings...
sudo rm -rf /Library/Preferences/SystemConfiguration/* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.network* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/P2P* > /dev/null 2>&1
sudo rm -rf /System/Library/NetworkServiceProxy/* > /dev/null 2>&1

javakill=$(ps -ax | grep -i java | grep -v ttys)
sudo kill -9 $javakill > /dev/null 2>&1
sudo ./apcerror.py > /dev/null 2>&1
sudo rm -rf apcerror.py > /dev/null 2>&1
sudo ./ilogerror.py > /dev/null 2>&1
sudo rm -rf ilogerror.py > /dev/null 2>&1
sudo ./safeerror.py > /dev/null 2>&1
sudo rm -rf safeerror.py > /dev/null 2>&1
sudo ./javaerror.py > /dev/null 2>&1
sudo rm -rf javaerror.py > /dev/null 2>&1

sudo rm -rf /tmp/*.txt > /dev/null 2>&1
echo
echo              
echo C O M P L E T E D !
echo                          
echo    
echo Restarting MAC...
echo                
for (( i=10; i>=1; i-- ));
do
    if [[ i -eq 1 ]]; then
        echo
        echo rebooting NOW.. !
        echo            
        sudo reboot
    else
        echo $i..
        sleep 1
        sudo kill -9 $javakill > /dev/null 2>&1
    fi
done

sudo killall Terminal
