#!/bin/bash
#   Created by WAH-IT PHL L2
#	*** FortiClient Reset Script ***

echo "*** FortiClient Reset Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

declare mDNS=(`ps -ax | grep -i mDNSResponder | grep -v ttys | awk '{print $1}'`)
declare FClient=(`ps -ax | grep -i Forti | grep -v ttys | awk '{print $1}'`)

echo Closing FortiClient...
for (( i=0; i<${#FClient[*]}; i++ ));
do
    sudo kill -9 ${FClient[$i]} > /dev/null 2>&1
done

sudo killall FortiClient > /dev/null 2>&1
      
echo Hang-Up mDNSResponder...
for (( i=0; i<${#mDNS[*]}; i++ ));
do
    sudo kill -HUP ${mDNS[$i]} > /dev/null 2>&1
done

echo              
echo Backing-up FortiClient profile...
sudo tar -C /Library/Application\ Support/Fortinet/FortiClient/conf/ -zcf ~/Desktop/vpn.bak vpn.plist
echo Removing all FortiClient services...
sudo rm -rf /Library/LaunchAgents/com.forti* > /dev/null 2>&1
echo Removing all FortiClient libraries...
sudo rm -rf ~/Library/Application\ Support/Forti* > /dev/null 2>&1
sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/conf/* > /dev/null 2>&1
sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/Logs/* > /dev/null 2>&1
sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/tmp/* > /dev/null 2>&1
echo Removing all FortiClient settings...
sudo rm -rf ~/Library/Application\ Support/com.forti* > /dev/null 2>&1
sudo rm -rf /Library/Application\ Support/com.forti* > /dev/null 2>&1
sudo rm -rf ~/Library/Saved\ Application\ State/com.forti*
sudo rm -rf /Library/Saved\ Application\ State/com.forti* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.forti* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.forti* > /dev/null 2>&1
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
echo                     

echo                 
echo Importing FortiClient profile...
sudo tar -xf ~/Desktop/vpn.bak -C /Library/Application\ Support/Fortinet/FortiClient/conf/
sleep 5
sudo rm -rf ~/Desktop/vpn.bak > /dev/null 2>&1
sudo rm -rf /tmp/Fortiprocess.txt > /dev/null 2>&1
echo Changing Ownership...
sudo chown -R root:wheel /Applications/FortiClient.app > /dev/null 2>&1
sleep 1
echo Changing Permissions...
sudo chmod -R 755 /Applications/FortiClient.app > /dev/null 2>&1

sudo rm -rf /tmp/*.txt > /dev/null 2>&1

echo           
echo C O M P L E T E D !
echo                          
echo  

for i in {0..4}; do
	sudo route -n flush
done

sudo ifconfig en0 down
sleep 1
sudo ifconfig en0 up
sleep 1

echo Closing Terminal in 5 secs...
for (( i=5; i>=1; i-- ));
do
    if [[ i -eq 1 ]]; then
        echo
        echo closing NOW.. !
        echo            
        sudo killall Terminal
    else
        echo $i..
        sleep 1
    fi
done
