#!/bin/bash
#Created by Mark Mon Monteros
#	*** FortiClient Reset Script ***

echo "*** FortiClient Reset Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

mDNS1=$(pgrep mDNSResponder | sed -n 1p)
mDNS2=$(pgrep mDNSResponder | sed -n 2p)
FortiPS=$(ps aux | grep -i Forti | grep -v ttys | awk '{print $2}' > /tmp/FortiPS.txt)

declare Forti=(`cat /tmp/FortiPS.txt`)

sudo tar -cf ~/Desktop/Forti.bak /Library/Application\ Support/Fortinet/FortiClient/conf/vpn.plist
echo Backing-up FortiClient profile...
sleep 2

echo Closing FortiClient...
countkForti=$(echo ${#Forti[*]})

for (( i=0; i<$countkForti; i++ ));
do
    sudo kill -9 ${Forti[$i]} > /dev/null 2>&1
done

sudo killall FortiClient > /dev/null 2>&1

echo             
echo Hang-Up mDNSResponder...
sudo kill -HUP $mDNS1 $mDNS2 > /dev/null 2>&1
echo Removing all FortiClient services...
sudo rm -rf ~/Library/LaunchAgents/com.forti* > /dev/null 2>&1
sudo rm -rf /Library/LaunchDaemons/com.forti* > /dev/null 2>&1
sudo rm -rf /Library/LaunchAgents/com.forti* > /dev/null 2>&1
echo Removing all FortiClient libraries...
sudo rm -rf ~/Library/Application\ Support/Forti* > /dev/null 2>&1
sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/Logs > /dev/null 2>&1
sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/data > /dev/null 2>&1
sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/ipsec > /dev/null 2>&1
sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/tmp > /dev/null 2>&1
echo Removing all FortiClient settings...
sudo rm -rf ~/Library/Application\ Support/com.forti* > /dev/null 2>&1
sudo rm -rf /Library/Application\ Support/com.forti* > /dev/null 2>&1
sudo rm -rf ~/Library/Saved\ Application\ State/com.forti*
sudo rm -rf /Library/Saved\ Application\ State/com.forti* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.forti* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.forti* > /dev/null 2>&1
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
echo Importing FortiClient profile...
sudo tar -xf ~/Desktop/Forti.bak -C /
sleep 5
sudo rm -rf ~/Desktop/Forti.bak > /dev/null 2>&1
sudo rm -rf /tmp/Fortiprocess.txt > /dev/null 2>&1
echo Changing Ownership...
sudo chown -R root:wheel /Applications/FortiClient.app > /dev/null 2>&1
sleep 1
echo Changing Permissions...
sudo chmod -R 755 /Applications/FortiClient.app > /dev/null 2>&1
sudo rm -rf /tmp/*.txt > /dev/null 2>&1

echo           
echo C O M P L E T E D !
echo                          
echo  

open /Applications/FortiClient.app
sudo killall Terminal