#!/bin/bash
#	Created by Mark Mon Monteros 
#	*** Messages Fix Script ***

echo "*** Messages Fix Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

declare mDNS=(`ps -ax | grep -i mDNSResponder | grep -v ttys | awk '{print$1}'`)
declare iMessage=(`ps -ax | grep -i Messages | grep -v ttys | awk '{print $1}'`)

echo Closing Messages...
for (( i=0; i<${#iMessage[*]}; i++ ));
do
    sudo kill -9 ${iMessage[$i]} > /dev/null 2>&1
done
sudo killall Messages > /dev/null 2>&1

echo Hang-Up mDNSResponder...
for (( i=0; i<${#mDNS[*]}; i++ ));
do
    sudo kill -HUP ${mDNS[$i]} > /dev/null 2>&1
done

echo          
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
echo Clearing Messages Settings...
sudo rm -rf /Library/Preferences/com.apple.iChat* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.imessage* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.Messages* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.imservice.iMessage* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.imservice.ids.iMessage* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.ichat* > /dev/null 2>&1
sudo rm -rf /Library/Preferences/com.apple.imagent.plist > /dev/null 2>&1

sudo rm -rf ~/Library/Preferences/com.apple.iChat* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.imessage* > /dev/null 2>&1
sudo rm -rf ~/Library/Prererences/com.apple.Messages* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.imservice.iMessage* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.imservice.ids.iMessage* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.ichat* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.imagent.plist > /dev/null 2>&1

sudo rm -rf ~/Library/Preferences/ByHost/com.apple.iChat* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/ByHost/com.apple.imessage* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/ByHost/com.apple.Messages* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/ByHost/com.apple.imservice.ids.iMessage* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/ByHost/com.apple.imservice.iMessage* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/ByHost/com.apple.ichat* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/ByHost/com.apple.imagent.plist > /dev/null 2>&1

echo Deleting Certificate "spark.concentrix.com"
sudo security delete-certificate -c "spark.concentrix.com" ~/Library/Keychains/login.keychain-db > /dev/null 2>&1
sudo security delete-certificate -c "spark.concentrix.com" /Library/Keychains/login.keychain-db > /dev/null 2>&1
#sudo rm -rf ~/dscache > /dev/null 2>&1
#sudo rm -rf /Library/Messages/* > /dev/null 2>&1
#sudo rm -rf ~/Library/Messages/* > /dev/null 2>&1
sudo killall Finder > /dev/null 2>&1

echo               
echo                
echo C O M P L E T E D !
echo                          
echo    
echo Closing Terminal in 5 secs...
for (( i=5; i>=1; i-- ));
do
    if [[ i -eq 1 ]]; then
        echo
        echo closing NOW.. !
        echo            
        sudo killall Terminal
    else
        echo $i..
        sleep 1
    fi
done