#!/bin/bash
#Created by Mark Mon Monteros
#	*** Refresh All Processes Script ***

echo "*** Refresh All Processes Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

declare mDNS=(`ps -ax | grep -i mDNSResponder | grep -v ttys | awk '{print$1}'`)
declare Sfari=(`ps -ax | grep -i Safari | grep -v ttys | awk '{print$1}'`)
declare SafeView=(`ps -ax | grep -i SafeView | grep -v ttys | awk '{print$1}'`)
declare iLog=(`ps -ax | grep -i iLog | grep -v ttys | awk '{print$1}'`)
declare Apple=(`ps -ax | grep -i AppleConnect | grep -v ttys | awk '{print$1}'`)
declare Avalon=(`ps -ax | grep -i Avalon | grep -v ttys | awk '{print$1}'`)
declare Adobe=(`ps -ax | grep -i Adobe | grep -v ttys | awk '{print$1}'`)
declare FClient=(`ps -ax | grep -i Forti | grep -v ttys | awk '{print$1}'`)

echo Closing Safari...
for (( i=0; i<${#Sfari[*]}; i++ ));
do
    sudo kill -9 ${Sfari[$i]} > /dev/null 2>&1
done
sudo killall Safari > /dev/null 2>&1

echo Closing SafeView...
for (( i=0; i<${#SafeView[*]}; i++ ));
do
    sudo kill -9 ${SafeView[$i]} > /dev/null 2>&1
done
sudo killall SafeView > /dev/null 2>&1

echo Closing iLog...
for (( i=0; i<${#iLog[*]}; i++ ));
do
    sudo kill -9 ${iLog[$i]} > /dev/null 2>&1
done
sudo killall iLog > /dev/null 2>&1

echo Closing AppleConnect...
for (( i=0; i<${#Apple[*]}; i++ ));
do
    sudo kill -9 ${Apple[$i]} > /dev/null 2>&1
done
sudo killall AppleConnectAgent > /dev/null 2>&1

echo Closing Avalon...
countkAvalon=$(echo ${#Avalon[*]})

for (( i=0; i<$countkAvalon; i++ ));
do
    sudo kill -9 ${Avalon[$i]} > /dev/null 2>&1
done
sudo killall Avalon > /dev/null 2>&1

echo Closing Adobe Connect...
for (( i=0; i<${#Adobe[*]}; i++ ));
do
    sudo kill -9 ${Adobe[$i]} > /dev/null 2>&1
done
sudo killall Adobe\ Connect > /dev/null 2>&1

echo Closing FortiClient...
for (( i=0; i<${#FClient[*]}; i++ ));
do
    sudo kill -9 ${FClient[$i]} > /dev/null 2>&1
done
sudo killall FortiClient > /dev/null 2>&1

echo Hang-Up mDNSResponder...
for (( i=0; i<${#mDNS[*]}; i++ ));
do
    sudo kill -HUP ${mDNS[$i]} > /dev/null 2>&1
done

echo    
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
sleep 3
echo Changing Ownership...
sudo chown -R root:wheel /Applications/SafeView.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/iLog.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/AppleConnect.app > /dev/null 2>&1
sudo chown -R root:wheel /Applications/FortiClient.app > /dev/null 2>&1
sleep 3
echo Changing Permissions...
sudo chmod -R 755 /Applications/SafeView.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/iLog.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/AppleConnect.app > /dev/null 2>&1
sudo chmod -R 755 /Applications/FortiClient.app > /dev/null 2>&1
sleep 2
echo
echo              

echo C O M P L E T E D !
echo                          
echo  
echo Closing Terminal in 5 secs...
for (( i=5; i>=1; i-- ));
do
    if [[ i -eq 1 ]]; then
        echo
        echo closing NOW.. !
        echo            
        sudo killall Terminal
    else
        echo $i..
        sleep 1
    fi
done