#!/bin/bash
#   Created by WAH-IT PHL L2
#	*** Safari Reset Script ***

echo "*** Safari Reset Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

declare mDNS=(`ps -ax | grep -i mDNSResponder | grep -v ttys | awk '{print$1}'`)
declare Sfari=(`ps -ax | grep -i Safari | grep -v ttys | awk '{print$1}'`)
declare FClient=(`ps -ax | grep -i Forti | grep -v ttys | awk '{print$1}'`)

echo Closing Safari...
for (( i=0; i<${#Sfari[*]}; i++ ));
do
    sudo kill -9 ${Sfari[$i]} > /dev/null 2>&1
done
sudo killall Safari > /dev/null 2>&1

echo Closing FortiClient...
for (( i=0; i<${#FClient[*]}; i++ ));
do
    sudo kill -9 ${FClient[$i]} > /dev/null 2>&1
done
sudo killall FortiClient > /dev/null 2>&1

echo Hang-Up mDNSResponder...
for (( i=0; i<${#mDNS[*]}; i++ ));
do
    sudo kill -HUP ${mDNS[$i]} > /dev/null 2>&1
done

echo               
echo Backing Up Safari Bookmarks...
sudo cp -R ~/Library/Safari/Bookmarks.plist ~/Desktop
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
echo Clearing COOKIES...
sudo rm -rf ~/Library/Cookies/* > /dev/null 2>&1
echo Clearing HISTORY...
sudo rm -rf ~/Library/Safari/* > /dev/null 2>&1
sudo rm -rf ~/Library/Saved\ Application\ State/* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Safari* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Web* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.commerce.safari* > /dev/null 2>&1
sudo rm -rf ~/Library/PubSub/Database/* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
sleep 3
echo Restoring Safari Bookmarks...
sudo mv ~/Desktop/Bookmarks.plist ~/Library/Safari/ > /dev/null 2>&1

echo
echo  
echo C O M P L E T E D !
echo                          
echo  
echo Closing Terminal in 5 secs...
for (( i=5; i>=1; i-- ));
do
    if [[ i -eq 1 ]]; then
        echo
        echo closing NOW.. !
        echo            
        sudo killall Terminal
    else
        echo $i..
        sleep 1
    fi
done