#!/bin/bash
#Created by Mark Mon Monteros
#	*** Safari Reset Script ***

echo "*** Safari Reset Script ***"
echo 'Enter your local password: "concentrix"'
sudo dscacheutil -flushcache
echo Flushing DNS . . .

mDNS1=$(pgrep mDNSResponder | sed -n 1p)
mDNS2=$(pgrep mDNSResponder | sed -n 2p)
SafariPS=$(ps aux | grep -i Safari | grep -v ttys | awk '{print $2}' > /tmp/SafariPS.txt)
FortiPS=$(ps aux | grep -i Forti | grep -v ttys | awk '{print $2}' > /tmp/FortiPS.txt)

declare Safari=(`cat /tmp/SafariPS.txt`)
declare Forti=(`cat /tmp/FortiPS.txt`)

echo Closing Safari...
countkSafari=$(echo ${#Safari[*]})

for (( i=0; i<$countkSafari; i++ ));
do
    sudo kill -9 ${Safari[$i]} > /dev/null 2>&1
done

echo Closing FortiClient...
countkForti=$(echo ${#Forti[*]})

for (( i=0; i<$countkForti; i++ ));
do
    sudo kill -9 ${Forti[$i]} > /dev/null 2>&1
done

sudo killall Safari > /dev/null 2>&1
sudo killall FortiClient > /dev/null 2>&1

echo Hang-Up mDNSResponder...
sudo kill -HUP $mDNS1 $mDNS2 > /dev/null 2>&1
echo Backing Up Safari Bookmarks...
sudo cp -R ~/Library/Safari/Bookmarks.plist ~/Desktop
echo Clearing CACHES...
sudo rm -rf /System/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /Library/Caches/* > /dev/null 2>&1
sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
echo Clearing COOKIES...
sudo rm -rf ~/Library/Cookies/* > /dev/null 2>&1
echo Clearing HISTORY...
sudo rm -rf ~/Library/Safari/* > /dev/null 2>&1
sudo rm -rf ~/Library/Saved\ Application\ State/* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Safari* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.Web* > /dev/null 2>&1
sudo rm -rf ~/Library/Preferences/com.apple.commerce.safari* > /dev/null 2>&1
sudo rm -rf ~/Library/PubSub/Database/* > /dev/null 2>&1
echo Removing Temporary Files...
sudo rm -rf ~/.temp* > /dev/null 2>&1
sleep 3
echo Restoring Safari Bookmarks...
sudo mv ~/Desktop/Bookmarks.plist ~/Library/Safari/ > /dev/null 2>&1
sudo rm -rf /tmp/*.txt > /dev/null 2>&1


echo C O M P L E T E !

sudo killall Terminal
