#!/bin/bash
#Created by Mark Mon Monteros
#	*** User Account Fix Script ***

echo "*** User Account Fix Script ***"
echo "Note: Use this script with CAUTION! Please don't run this if there aren't any user account issues..."
echo
echo Before proceeding.. Make sure you are logged in to an administrator user account: 'admin', 'localadmin', '_casper'
echo Or you can use the terminal command: login
echo                         
echo 'Enter your local password: "concentrix"'

sudo rm -rf /tmp/*.txt > /dev/null 2>&1
#GET ACCOUNT NAME + NFSHOMEDIR
accList=$(sudo dscl . -list /Users NFSHomeDirectory | grep ./Users | grep -v ./observe$ | grep -v ./admin$ | grep -v ./localadmin$ | grep -v ./cnxadmin$ | grep -v ./a$ | grep -v ./Shared$ > /tmp/accList.txt)

#GET USER PATH
sleep 2
userList=$(ls -l /Users | awk {'print$5 " " $9'} | sed -n '1!p' | sort -n | awk '{print$2}' | grep -v ^a$ | grep -v ^localadmin$ | grep -v ^cnxadmin$ | grep -v ^admin$ | grep -v ^Shared$ > /tmp/userList.txt)
sleep 2

#COUNT NUMBER OF ACCOUNTS
countAcc=$(cat /tmp/accList.txt | wc -l)
    acc1=$(cat /tmp/accList.txt | sed -n 1p | awk {'print$1}')
    acc2=$(cat /tmp/accList.txt | sed -n 2p | awk {'print$1}')
    acc3=$(cat /tmp/accList.txt | sed -n 3p | awk {'print$1}')
    acc4=$(cat /tmp/accList.txt | sed -n 4p | awk {'print$1}')
    acc5=$(cat /tmp/accList.txt | sed -n 5p | awk {'print$1}')
    acc6=$(cat /tmp/accList.txt | sed -n 6p | awk {'print$1}')
if [[ $countAcc -eq 6 ]]; then
    /usr/bin/dscl . -read /Users/"$acc1" | grep RecordName | awk {'print$2'} > /tmp/getRN1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep RecordName | awk {'print$2'} > /tmp/getRN2.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc3" | grep RecordName | awk {'print$2'} > /tmp/getRN3.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc4" | grep RecordName | awk {'print$2'} > /tmp/getRN4.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc5" | grep RecordName | awk {'print$2'} > /tmp/getRN5.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc6" | grep RecordName | awk {'print$2'} > /tmp/getRN6.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc1" | grep NFS | awk {'print$2'} > /tmp/getNFS1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep NFS | awk {'print$2'} > /tmp/getNFS2.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc3" | grep NFS | awk {'print$2'} > /tmp/getNFS3.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc4" | grep NFS | awk {'print$2'} > /tmp/getNFS4.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc5" | grep NFS | awk {'print$2'} > /tmp/getNFS5.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc6" | grep NFS | awk {'print$2'} > /tmp/getNFS6.txt
    sleep 2
    echo "6 Accounts here: " `cat /tmp/getRN1.txt` `cat /tmp/getRN2.txt` `cat /tmp/getRN3.txt` `cat /tmp/getRN4.txt` `cat /tmp/getRN5.txt` `cat /tmp/getRN6.txt`
    echo "6 Accounts homedir: " `cat /tmp/getNFS1.txt` `cat /tmp/getNFS2.txt` `cat /tmp/getNFS3.txt` `cat /tmp/getNFS4.txt` `cat /tmp/getNFS5.txt` `cat /tmp/getNFS6.txt`
elif [[ $countAcc -eq 5 ]]; then
    sudo /usr/bin/dscl . -read /Users/"$acc1"* | grep RecordName | awk {'print$2'} > /tmp/getRN1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep RecordName | awk {'print$2'} > /tmp/getRN2.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc3" | grep RecordName | awk {'print$2'} > /tmp/getRN3.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc4" | grep RecordName | awk {'print$2'} > /tmp/getRN4.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc5" | grep RecordName | awk {'print$2'} > /tmp/getRN5.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc1" | grep NFS | awk {'print$2'} > /tmp/getNFS1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep NFS | awk {'print$2'} > /tmp/getNFS2.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc3" | grep NFS | awk {'print$2'} > /tmp/getNFS3.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc4" | grep NFS | awk {'print$2'} > /tmp/getNFS4.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc5" | grep NFS | awk {'print$2'} > /tmp/getNFS5.txt
    sleep 2
    echo "5 Accounts here: " `cat /tmp/getRN1.txt` `cat /tmp/getRN2.txt` `cat /tmp/getRN3.txt` `cat /tmp/getRN4.txt` `cat /tmp/getRN5.txt`
    echo "5 Accounts homedir: " `cat /tmp/getNFS1.txt` `cat /tmp/getNFS2.txt` `cat /tmp/getNFS3.txt` `cat /tmp/getNFS4.txt` `cat /tmp/getNFS5.txt`
elif [[ $countAcc -eq 4 ]]; then
    /usr/bin/dscl . -read /Users/"$acc1" | grep RecordName | awk {'print$2'} > /tmp/getRN1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep RecordName | awk {'print$2'} > /tmp/getRN2.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc3" | grep RecordName | awk {'print$2'} > /tmp/getRN3.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc4" | grep RecordName | awk {'print$2'} > /tmp/getRN4.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc1" | grep NFS | awk {'print$2'} > /tmp/getNFS1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep NFS | awk {'print$2'} > /tmp/getNFS2.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc3" | grep NFS | awk {'print$2'} > /tmp/getNFS3.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc4" | grep NFS | awk {'print$2'} > /tmp/getNFS4.txt
    sleep 2
    echo "4 Accounts here: " `cat /tmp/getRN1.txt` `cat /tmp/getRN2.txt` `cat /tmp/getRN3.txt` `cat /tmp/getRN4.txt`
    echo "4 Accounts homedir: " `cat /tmp/getNFS1.txt` `cat /tmp/getNFS2.txt` `cat /tmp/getNFS3.txt` `cat /tmp/getNFS4.txt`
elif [[ $countAcc -eq 3 ]]; then
    /usr/bin/dscl . -read /Users/"$acc1" | grep RecordName | awk {'print$2'} > /tmp/getRN1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep RecordName | awk {'print$2'} > /tmp/getRN2.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc3" | grep RecordName | awk {'print$2'} > /tmp/getRN3.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc1" | grep NFS | awk {'print$2'} > /tmp/getNFS1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep NFS | awk {'print$2'} > /tmp/getNFS2.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc3" | grep NFS | awk {'print$2'} > /tmp/getNFS3.txt
    sleep 2
    echo "3 Accounts here: " `cat /tmp/getRN1.txt` `cat /tmp/getRN2.txt` `cat /tmp/getRN3.txt`
    echo "3 Accounts homedir: " `cat /tmp/getNFS1.txt` `cat /tmp/getNFS2.txt` `cat /tmp/getNFS3.txt`
elif [[ $countAcc -eq 2 ]]; then
    /usr/bin/dscl . -read /Users/"$acc1" | grep RecordName | awk {'print$2'} > /tmp/getRN1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep RecordName | awk {'print$2'} > /tmp/getRN2.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc1" | grep NFS | awk {'print$2'} > /tmp/getNFS1.txt
    sleep 2
    /usr/bin/dscl . -read /Users/"$acc2" | grep NFS | awk {'print$2'} > /tmp/getNFS2.txt
    sleep 2
    echo "2 Accounts here: " `cat /tmp/getRN1.txt` `cat /tmp/getRN2.txt`
    echo "2 Accounts homedir: " `cat /tmp/getNFS1.txt` `cat /tmp/getNFS2.txt`
else echo "NO OTHER ACCOUNTS DETECTED"
fi

#Remove Other Home Folders
countUsers=$(cat /tmp/userList.txt | wc -l)
delUsers=$(cat /tmp/userList.txt | head -n $(($countUsers -1)) > /tmp/delUsers.txt)
sleep 2
delUsersFilt=$(cat /tmp/delUsers.txt | grep -v ^a$ | grep -v ^localadmin$ | grep -v ^cnxadmin$ | grep -v ^admin$ | grep -v ^Shared$ > /tmp/delList.txt)
sleep 2
delUser1=$(cat /tmp/delList.txt | sed -n 1p)
delUser2=$(cat /tmp/delList.txt | sed -n 2p)
delUser3=$(cat /tmp/delList.txt | sed -n 3p)
delUser4=$(cat /tmp/delList.txt | sed -n 4p)
delUser5=$(cat /tmp/delList.txt | sed -n 5p)
delUser6=$(cat /tmp/delList.txt | sed -n 6p)
delUser7=$(cat /tmp/delList.txt | sed -n 7p)
delUser8=$(cat /tmp/delList.txt | sed -n 8p)
delUser9=$(cat /tmp/delList.txt | sed -n 9p)

echo Removing other home folders...
sudo rm -rf /Users/"$delUser1"/
sleep 2
sudo rm -rf /Users/"$delUser2"/
sleep 2
sudo rm -rf /Users/"$delUser3"/
sleep 2 
sudo rm -rf /Users/"$delUser4"/
sleep 2
sudo rm -rf /Users/"$delUser5"/
sleep 2
sudo rm -rf /Users/"$delUser6"/
sleep 2
sudo rm -rf /Users/"$delUser7"/
sleep 2
sudo rm -rf /Users/"$delUser8"/
sleep 2
sudo rm -rf /Users/"$delUser9"/
sleep 2
echo "/User directories removed:" $delUser1 $delUser2 $delUser3 $delUser4 $delUser5 $delUser6 $delUser7 $delUser8 $delUser9

#Get True User Account
trueUser=$(cat /tmp/userList.txt | tail -n 1)
matchAccPath1=$(cat /tmp/getNFS1.txt | cut -d / -f3)
matchAccPath2=$(cat /tmp/getNFS2.txt | cut -d / -f3)
matchAccPath3=$(cat /tmp/getNFS3.txt | cut -d / -f3)
matchAccPath4=$(cat /tmp/getNFS4.txt | cut -d / -f3)
matchAccPath5=$(cat /tmp/getNFS5.txt | cut -d / -f3)
matchAccPath6=$(cat /tmp/getNFS6.txt | cut -d / -f3)
getRN1=$(cat /tmp/getRN1.txt | cut -d / -f3)
getRN2=$(cat /tmp/getRN2.txt | cut -d / -f3)
getRN3=$(cat /tmp/getRN3.txt | cut -d / -f3)
getRN4=$(cat /tmp/getRN4.txt | cut -d / -f3)
getRN5=$(cat /tmp/getRN5.txt | cut -d / -f3)
getRN6=$(cat /tmp/getRN6.txt | cut -d / -f3)
trueAcc=$(/usr/bin/dscl . -list /Users NFSHomeDirectory | grep /Users/"$trueUser" | awk '{print$1}')
trueRealN=$(/usr/bin/dscl . -read /Users/"$trueAcc" RealName | awk '{print$2}')
trueRN=$(/usr/bin/dscl . -read /Users/"$trueAcc" RecordName | awk '{print$2}')
trueNFS=$(/usr/bin/dscl . -read /Users/"$trueAcc" NFSHomeDirectory | awk '{print$2}')
sleep 1

echo        
echo Matching Account Name and User Path...

if [[ "$trueUser" == "$matchAccPath1" ]]; then
    echo Match Found: $matchAccPath1
    echo Removing Other Accounts...
    sudo /usr/bin/dscl . -delete /Users/"$getRN2"
    sudo /usr/bin/dscl . -delete /Users/"$getRN3"
    sudo /usr/bin/dscl . -delete /Users/"$getRN4"
    sudo /usr/bin/dscl . -delete /Users/"$getRN5"
    sudo /usr/bin/dscl . -delete /Users/"$getRN6"
    echo $getRN2 $getRN3 $getRN4 $getRN5 $getRN6 accounts removed..
    sleep 1
    echo Migrating $trueUser Account to WorkAtHomeAgent Account
    sudo /usr/bin/dscl . -change /Users/"getRN1" RealName "$trueRN" "WorkAtHomeAgent"
    sudo /usr/bin/dscl . -change /Users/"getRN1" RecordName $trueRN workathomeagent
    sudo /usr/bin/dscl . -change /Users/"getRN1" NFSHomeDirectory "$trueNFS" /Users/workathomeagent
    echo Migration complete..
elif [[ "$trueUser" == "$matchAccPath2" ]]; then
    echo Match Found: $matchAccPath2
    echo Removing Other Accounts...
    sudo /usr/bin/dscl . -delete /Users/"$getRN1"
    sudo /usr/bin/dscl . -delete /Users/"$getRN3"
    sudo /usr/bin/dscl . -delete /Users/"$getRN4"
    sudo /usr/bin/dscl . -delete /Users/"$getRN5"
    sudo /usr/bin/dscl . -delete /Users/"$getRN6"
    echo $getRN1 $getRN3 $getRN4 $getRN5 $getRN6 accounts removed..
    sleep 1
    echo Migrating $trueUser Account to WorkAtHomeAgent Account
    sudo /usr/bin/dscl . -change /Users/"getRN2" RealName "$trueRN" "WorkAtHomeAgent"
    sudo /usr/bin/dscl . -change /Users/"getRN2" RecordName $trueRN workathomeagent
    sudo /usr/bin/dscl . -change /Users/"getRN2" NFSHomeDirectory "$trueNFS" /Users/workathomeagent
    echo Migration complete..
elif [[ "$trueUser" == "$matchAccPath3" ]]; then
    echo Match Found: $matchAccPath3
    echo Removing Other Accounts...
    sudo /usr/bin/dscl . -delete /Users/"$getRN1"
    sudo /usr/bin/dscl . -delete /Users/"$getRN2"
    sudo /usr/bin/dscl . -delete /Users/"$getRN4"
    sudo /usr/bin/dscl . -delete /Users/"$getRN5"
    sudo /usr/bin/dscl . -delete /Users/"$getRN6"
    echo $getRN1 $getRN2 $getRN4 $getRN5 $getRN6 accounts removed..
    sleep 1
    echo Migrating $trueUser Account to WorkAtHomeAgent Account
    sudo /usr/bin/dscl . -change /Users/"getRN3" RealName "$trueRN" "WorkAtHomeAgent"
    sudo /usr/bin/dscl . -change /Users/"getRN3" RecordName $trueRN workathomeagent
    sudo /usr/bin/dscl . -change /Users/"getRN3" NFSHomeDirectory "$trueNFS" /Users/workathomeagent
    echo Migration complete..
elif [[ "$trueUser" == "$matchAccPath4" ]]; then
    echo Match Found: $matchAccPath4
    echo Removing Other Accounts...
    sudo /usr/bin/dscl . -delete /Users/"$getRN1"
    sudo /usr/bin/dscl . -delete /Users/"$getRN2"
    sudo /usr/bin/dscl . -delete /Users/"$getRN3"
    sudo /usr/bin/dscl . -delete /Users/"$getRN5"
    sudo /usr/bin/dscl . -delete /Users/"$getRN6"
    echo $getRN1 $getRN2 $getRN3 $getRN5 $getRN6 accounts removed..
    sleep 1
    echo Migrating $trueUser Account to WorkAtHomeAgent Account
    sudo /usr/bin/dscl . -change /Users/"getRN4" RealName "$trueRN" "WorkAtHomeAgent"
    sudo /usr/bin/dscl . -change /Users/"getRN4" RecordName $trueRN workathomeagent
    sudo /usr/bin/dscl . -change /Users/"getRN4" NFSHomeDirectory "$trueNFS" /Users/workathomeagent
    echo Migration complete..
elif [[ "$trueUser" == "$matchAccPath5" ]]; then
    echo Match Found: $matchAccPath5
    echo Removing Other Accounts...
    sudo /usr/bin/dscl . -delete /Users/"$getRN1"
    sudo /usr/bin/dscl . -delete /Users/"$getRN2"
    sudo /usr/bin/dscl . -delete /Users/"$getRN3"
    sudo /usr/bin/dscl . -delete /Users/"$getRN4"
    sudo /usr/bin/dscl . -delete /Users/"$getRN6"
    echo $getRN1 $getRN2 $getRN3 $getRN4 $getRN6 accounts removed..
    sleep 1
    echo Migrating $trueUser Account to WorkAtHomeAgent Account
    sudo /usr/bin/dscl . -change /Users/"getRN5" RealName "$trueRN" "WorkAtHomeAgent"
    sudo /usr/bin/dscl . -change /Users/"getRN5" RecordName $trueRN workathomeagent
    sudo /usr/bin/dscl . -change /Users/"getRN5" NFSHomeDirectory "$trueNFS" /Users/workathomeagent
    echo Migration complete..
elif [[ "$trueUser" == "$matchAccPath6" ]]; then
    echo Match Found: $matchAccPath6
    echo Removing Other Accounts...
    sudo /usr/bin/dscl . -delete /Users/"$getRN1"
    sudo /usr/bin/dscl . -delete /Users/"$getRN2"
    sudo /usr/bin/dscl . -delete /Users/"$getRN3"
    sudo /usr/bin/dscl . -delete /Users/"$getRN4"
    sudo /usr/bin/dscl . -delete /Users/"$getRN5"
    echo $getRN1 $getRN2 $getRN3 $getRN4 $getRN5 accounts removed..
    sleep 1
    echo Migrating $trueUser Account to WorkAtHomeAgent Account
    sudo /usr/bin/dscl . -change /Users/"getRN6" RealName "$trueRN" "WorkAtHomeAgent"
    sudo /usr/bin/dscl . -change /Users/"getRN6" RecordName $trueRN workathomeagent
    sudo /usr/bin/dscl . -change /Users/"getRN6" NFSHomeDirectory "$trueNFS" /Users/workathomeagent
    echo Migration complete..
else echo "No Matching User Account Found"
fi

echo                              
echo Renaming /Users/$trueUser to /Users/workathomeagent
sudo mv /Users/"$trueUser" /Users/workathomeagent
sleep 1
echo Changing Ownership and Permissions...
sudo chown -R workathomeagent /Users/workathomeagent
sudo chmod -R 755 /Users/workathomeagent
sleep 5

#sudo rm -rf /tmp/*.txt > /dev/null 2>&1
echo                    
echo               
echo C O M P L E T E D !
echo                          
echo    
echo Restarting MAC...
echo                
for (( i=10; i>=1; i-- ));
do
    if [[ i -eq 1 ]]; then
        echo
        echo rebooting .. !
        echo            
        sudo reboot
    else
        echo $i..
        sleep 1
    fi
done
